# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Musings on Software vs. People
email: ceph3us@users.github.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring how people interact with computers and the ways it needs improvement,
  as well as occasional ramblings on things I'm working with or on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ceph3.us" # the base hostname & protocol for your site
twitter_username: ceph3us
github_username:  ceph3us

# Build settings
markdown: kramdown
include:
  - .nojekyll
  - CNAME